# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.6)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6...3.21)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget rabbitmq::rabbitmq rabbitmq::rabbitmq-static)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target rabbitmq::rabbitmq
add_library(rabbitmq::rabbitmq SHARED IMPORTED)

set_target_properties(rabbitmq::rabbitmq PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/../include;D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/../include"
)

# Create imported target rabbitmq::rabbitmq-static
add_library(rabbitmq::rabbitmq-static STATIC IMPORTED)

set_target_properties(rabbitmq::rabbitmq-static PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "AMQP_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/../include;D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/../include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:ws2_32>"
)

# Import target "rabbitmq::rabbitmq" for configuration "Debug"
set_property(TARGET rabbitmq::rabbitmq APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(rabbitmq::rabbitmq PROPERTIES
  IMPORTED_IMPLIB_DEBUG "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Debug/rabbitmq.4.lib"
  IMPORTED_LOCATION_DEBUG "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Debug/rabbitmq.4.dll"
  )

# Import target "rabbitmq::rabbitmq-static" for configuration "Debug"
set_property(TARGET rabbitmq::rabbitmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(rabbitmq::rabbitmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "C"
  IMPORTED_LOCATION_DEBUG "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Debug/librabbitmq.4.lib"
  )

# Import target "rabbitmq::rabbitmq" for configuration "Release"
set_property(TARGET rabbitmq::rabbitmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(rabbitmq::rabbitmq PROPERTIES
  IMPORTED_IMPLIB_RELEASE "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Release/rabbitmq.4.lib"
  IMPORTED_LOCATION_RELEASE "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Release/rabbitmq.4.dll"
  )

# Import target "rabbitmq::rabbitmq-static" for configuration "Release"
set_property(TARGET rabbitmq::rabbitmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(rabbitmq::rabbitmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/Release/librabbitmq.4.lib"
  )

# Import target "rabbitmq::rabbitmq" for configuration "MinSizeRel"
set_property(TARGET rabbitmq::rabbitmq APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(rabbitmq::rabbitmq PROPERTIES
  IMPORTED_IMPLIB_MINSIZEREL "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/MinSizeRel/rabbitmq.4.lib"
  IMPORTED_LOCATION_MINSIZEREL "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/MinSizeRel/rabbitmq.4.dll"
  )

# Import target "rabbitmq::rabbitmq-static" for configuration "MinSizeRel"
set_property(TARGET rabbitmq::rabbitmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS MINSIZEREL)
set_target_properties(rabbitmq::rabbitmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_MINSIZEREL "C"
  IMPORTED_LOCATION_MINSIZEREL "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/MinSizeRel/librabbitmq.4.lib"
  )

# Import target "rabbitmq::rabbitmq" for configuration "RelWithDebInfo"
set_property(TARGET rabbitmq::rabbitmq APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(rabbitmq::rabbitmq PROPERTIES
  IMPORTED_IMPLIB_RELWITHDEBINFO "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/RelWithDebInfo/rabbitmq.4.lib"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/RelWithDebInfo/rabbitmq.4.dll"
  )

# Import target "rabbitmq::rabbitmq-static" for configuration "RelWithDebInfo"
set_property(TARGET rabbitmq::rabbitmq-static APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(rabbitmq::rabbitmq-static PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELWITHDEBINFO "C"
  IMPORTED_LOCATION_RELWITHDEBINFO "D:/Projects/C-RabbitMQ/RabbitMQ+C/librabbitmq/RelWithDebInfo/librabbitmq.4.lib"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
